// <auto-generated />
using System;
using Dataportal.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dataportal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250701143529_AddingBoolValues")]
    partial class AddingBoolValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dataportal.Models.Appareil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Capacite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Appareil");
                });

            modelBuilder.Entity("Dataportal.Models.DemandeDeCompte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("EmailVerifie")
                        .HasColumnType("bit");

                    b.Property<int>("IdEntreprise")
                        .HasColumnType("int");

                    b.Property<int>("IdStatutDeLaDemande")
                        .HasColumnType("int");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdEntreprise");

                    b.HasIndex("IdStatutDeLaDemande");

                    b.ToTable("DemandeDeCompte");
                });

            modelBuilder.Entity("Dataportal.Models.DomaineEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Domaine")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("DomaineActif")
                        .HasColumnType("bit");

                    b.Property<int>("IdEntreprise")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdEntreprise");

                    b.ToTable("DomaineEmail");
                });

            modelBuilder.Entity("Dataportal.Models.Donnees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateAjouter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("FrequenceDeCollect")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdMetadonnee")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomDeLaTable")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NombreDeCapteurs")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTimestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.HasIndex("NomDeLaTable")
                        .IsUnique();

                    b.ToTable("Donnees");
                });

            modelBuilder.Entity("Dataportal.Models.DonneesContexteEnvironnemental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateAjouter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdMetadonnee")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomDeLaTable")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartTimestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.HasIndex("NomDeLaTable")
                        .IsUnique();

                    b.ToTable("DonneesContexteEnvironnemental");
                });

            modelBuilder.Entity("Dataportal.Models.DonneesEventLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateAjouter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdMetadonnee")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomDeLaTable")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NombreDEvents")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTimestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.HasIndex("NomDeLaTable")
                        .IsUnique();

                    b.ToTable("DonneesEventLogs");
                });

            modelBuilder.Entity("Dataportal.Models.Entreprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Entreprise");
                });

            modelBuilder.Entity("Dataportal.Models.Historique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("IdMetadonnee")
                        .HasColumnType("int");

                    b.Property<string>("Lien")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdMetadonnee");

                    b.ToTable("Historique");
                });

            modelBuilder.Entity("Dataportal.Models.Licence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("Licence");
                });

            modelBuilder.Entity("Dataportal.Models.Metadonnee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Anonymiser")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoriserApi")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoriserLeTelechargement")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoriserLesSQL")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DernierMiseAJour")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDocumentation")
                        .HasColumnType("int");

                    b.Property<int>("IdDonnees")
                        .HasColumnType("int");

                    b.Property<int>("IdDonneesContexteEnvironnemental")
                        .HasColumnType("int");

                    b.Property<int>("IdDonneesEventLogs")
                        .HasColumnType("int");

                    b.Property<int>("IdLicence")
                        .HasColumnType("int");

                    b.Property<int>("IdSite")
                        .HasColumnType("int");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<int>("IdVisibilite")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NombreDeTelechargements")
                        .HasColumnType("int");

                    b.Property<int>("QualiteDesDonnees")
                        .HasColumnType("int");

                    b.Property<bool>("SeriesTemporelles")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("TailleDesDonnees")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("VisualiserLesdonnees")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdDonnees")
                        .IsUnique();

                    b.HasIndex("IdDonneesContexteEnvironnemental")
                        .IsUnique();

                    b.HasIndex("IdDonneesEventLogs")
                        .IsUnique();

                    b.HasIndex("IdLicence");

                    b.HasIndex("IdSite");

                    b.HasIndex("IdUtilisateur");

                    b.HasIndex("IdVisibilite");

                    b.ToTable("Metadonnee");
                });

            modelBuilder.Entity("Dataportal.Models.Metadonnee_Appareil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdAppareil")
                        .HasColumnType("int");

                    b.Property<int>("IdAppareilDansDonnees")
                        .HasColumnType("int");

                    b.Property<int>("IdMetadonnee")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAppareil");

                    b.HasIndex("IdMetadonnee");

                    b.ToTable("Metadonnee_Appareil");
                });

            modelBuilder.Entity("Dataportal.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Dataportal.Models.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Emplacement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Site");
                });

            modelBuilder.Entity("Dataportal.Models.StatutDeLaDemande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("StatutDeLaDemande");
                });

            modelBuilder.Entity("Dataportal.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CompteActif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateApprobation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DernierLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionProfil")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FinLockout")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEntreprise")
                        .HasColumnType("int");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<string>("LienLinkedIn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbrEchecsAcces")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdEntreprise");

                    b.HasIndex("IdRole");

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("Dataportal.Models.Visibilite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("Visibilite");
                });

            modelBuilder.Entity("Dataportal.Models.DemandeDeCompte", b =>
                {
                    b.HasOne("Dataportal.Models.Entreprise", "Entreprise")
                        .WithMany("DemandeDeComptes")
                        .HasForeignKey("IdEntreprise")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dataportal.Models.StatutDeLaDemande", "StatutDeLaDemande")
                        .WithMany("DemandeDeComptes")
                        .HasForeignKey("IdStatutDeLaDemande")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entreprise");

                    b.Navigation("StatutDeLaDemande");
                });

            modelBuilder.Entity("Dataportal.Models.DomaineEmail", b =>
                {
                    b.HasOne("Dataportal.Models.Entreprise", "Entreprise")
                        .WithMany("DomaineEmails")
                        .HasForeignKey("IdEntreprise")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("Dataportal.Models.Historique", b =>
                {
                    b.HasOne("Dataportal.Models.Metadonnee", "Metadonnee")
                        .WithMany("Historiques")
                        .HasForeignKey("IdMetadonnee")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Metadonnee");
                });

            modelBuilder.Entity("Dataportal.Models.Metadonnee", b =>
                {
                    b.HasOne("Dataportal.Models.Donnees", "Donnees")
                        .WithOne("Metadonnee")
                        .HasForeignKey("Dataportal.Models.Metadonnee", "IdDonnees")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dataportal.Models.DonneesContexteEnvironnemental", "DonneesContexteEnvironnemental")
                        .WithOne("Metadonnee")
                        .HasForeignKey("Dataportal.Models.Metadonnee", "IdDonneesContexteEnvironnemental")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dataportal.Models.DonneesEventLogs", "DonneesEventLogs")
                        .WithOne("Metadonnee")
                        .HasForeignKey("Dataportal.Models.Metadonnee", "IdDonneesEventLogs")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dataportal.Models.Licence", "Licence")
                        .WithMany("Metadonnees")
                        .HasForeignKey("IdLicence")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dataportal.Models.Site", "Site")
                        .WithMany("Metadonnees")
                        .HasForeignKey("IdSite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dataportal.Models.Utilisateur", "Utilisateur")
                        .WithMany("Metadonnees")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dataportal.Models.Visibilite", "Visibilite")
                        .WithMany("Metadonnees")
                        .HasForeignKey("IdVisibilite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donnees");

                    b.Navigation("DonneesContexteEnvironnemental");

                    b.Navigation("DonneesEventLogs");

                    b.Navigation("Licence");

                    b.Navigation("Site");

                    b.Navigation("Utilisateur");

                    b.Navigation("Visibilite");
                });

            modelBuilder.Entity("Dataportal.Models.Metadonnee_Appareil", b =>
                {
                    b.HasOne("Dataportal.Models.Appareil", "Appareil")
                        .WithMany("Metadonnee_Appareils")
                        .HasForeignKey("IdAppareil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dataportal.Models.Metadonnee", "Metadonnee")
                        .WithMany("Metadonnee_Appareils")
                        .HasForeignKey("IdMetadonnee")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appareil");

                    b.Navigation("Metadonnee");
                });

            modelBuilder.Entity("Dataportal.Models.Utilisateur", b =>
                {
                    b.HasOne("Dataportal.Models.Entreprise", "Entreprise")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("IdEntreprise")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dataportal.Models.Role", "Role")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entreprise");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Dataportal.Models.Appareil", b =>
                {
                    b.Navigation("Metadonnee_Appareils");
                });

            modelBuilder.Entity("Dataportal.Models.Donnees", b =>
                {
                    b.Navigation("Metadonnee")
                        .IsRequired();
                });

            modelBuilder.Entity("Dataportal.Models.DonneesContexteEnvironnemental", b =>
                {
                    b.Navigation("Metadonnee")
                        .IsRequired();
                });

            modelBuilder.Entity("Dataportal.Models.DonneesEventLogs", b =>
                {
                    b.Navigation("Metadonnee")
                        .IsRequired();
                });

            modelBuilder.Entity("Dataportal.Models.Entreprise", b =>
                {
                    b.Navigation("DemandeDeComptes");

                    b.Navigation("DomaineEmails");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("Dataportal.Models.Licence", b =>
                {
                    b.Navigation("Metadonnees");
                });

            modelBuilder.Entity("Dataportal.Models.Metadonnee", b =>
                {
                    b.Navigation("Historiques");

                    b.Navigation("Metadonnee_Appareils");
                });

            modelBuilder.Entity("Dataportal.Models.Role", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("Dataportal.Models.Site", b =>
                {
                    b.Navigation("Metadonnees");
                });

            modelBuilder.Entity("Dataportal.Models.StatutDeLaDemande", b =>
                {
                    b.Navigation("DemandeDeComptes");
                });

            modelBuilder.Entity("Dataportal.Models.Utilisateur", b =>
                {
                    b.Navigation("Metadonnees");
                });

            modelBuilder.Entity("Dataportal.Models.Visibilite", b =>
                {
                    b.Navigation("Metadonnees");
                });
#pragma warning restore 612, 618
        }
    }
}
