// <auto-generated />
using System;
using Dataportal.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dataportal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260127200040_AddIndexMetadata")]
    partial class AddIndexMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dataportal.Models.Appareil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Capacite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Appareil");
                });

            modelBuilder.Entity("Dataportal.Models.DemandeDeCompte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("EmailVerifie")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EmailVerifieLe")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEntreprise")
                        .HasColumnType("int");

                    b.Property<int>("IdStatutDeLaDemande")
                        .HasColumnType("int");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("VerificationTokenExpiration")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdEntreprise");

                    b.HasIndex("IdStatutDeLaDemande");

                    b.ToTable("DemandeDeCompte");
                });

            modelBuilder.Entity("Dataportal.Models.DomaineEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Domaine")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("DomaineActif")
                        .HasColumnType("bit");

                    b.Property<int>("IdEntreprise")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdEntreprise");

                    b.ToTable("DomaineEmail");
                });

            modelBuilder.Entity("Dataportal.Models.Donnees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateAjouter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("FrequenceDeCollect")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdMetadonnee")
                        .HasColumnType("int");

                    b.Property<int>("IdQualiteDonnees")
                        .HasColumnType("int");

                    b.Property<bool>("IndexEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("IndexError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IndexIdColumn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IndexIncludeColumn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IndexName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IndexStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IndexTimeColumn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IndexType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomDeLaTable")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NombreDeCapteurs")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTimestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdQualiteDonnees");

                    b.HasIndex("NomDeLaTable")
                        .IsUnique();

                    b.HasIndex("Libelle", "Code")
                        .IsUnique();

                    b.ToTable("Donnees");
                });

            modelBuilder.Entity("Dataportal.Models.DonneesContexteEnvironnemental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateAjouter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdMetadonnee")
                        .HasColumnType("int");

                    b.Property<int>("IdQualiteDonnees")
                        .HasColumnType("int");

                    b.Property<bool>("IndexEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("IndexError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IndexIdColumn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IndexIncludeColumn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IndexName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IndexStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IndexTimeColumn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IndexType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomDeLaTable")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartTimestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdQualiteDonnees");

                    b.HasIndex("NomDeLaTable")
                        .IsUnique();

                    b.HasIndex("Libelle", "Code")
                        .IsUnique();

                    b.ToTable("DonneesContexteEnvironnemental");
                });

            modelBuilder.Entity("Dataportal.Models.DonneesEventLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateAjouter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdMetadonnee")
                        .HasColumnType("int");

                    b.Property<int>("IdQualiteDonnees")
                        .HasColumnType("int");

                    b.Property<bool>("IndexEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("IndexError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IndexIdColumn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IndexIncludeColumn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IndexName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IndexStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IndexTimeColumn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IndexType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomDeLaTable")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NombreDEvents")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTimestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdQualiteDonnees");

                    b.HasIndex("NomDeLaTable")
                        .IsUnique();

                    b.HasIndex("Libelle", "Code")
                        .IsUnique();

                    b.ToTable("DonneesEventLogs");
                });

            modelBuilder.Entity("Dataportal.Models.Entreprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Entreprise");
                });

            modelBuilder.Entity("Dataportal.Models.FichierStocke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoriserLeTelechargement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DateAjout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("IdLicence")
                        .HasColumnType("int");

                    b.Property<int?>("IdTypeEnergieRenouvelable")
                        .HasColumnType("int");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<int>("IdVisibilite")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomFichierOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NomFichierStocke")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("NombreDeTelechargements")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long>("TailleOctets")
                        .HasColumnType("bigint");

                    b.Property<string>("TypeContenu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdLicence");

                    b.HasIndex("IdTypeEnergieRenouvelable");

                    b.HasIndex("IdUtilisateur");

                    b.HasIndex("IdVisibilite");

                    b.ToTable("FichierStocke");
                });

            modelBuilder.Entity("Dataportal.Models.Licence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("Licence");
                });

            modelBuilder.Entity("Dataportal.Models.MessageAccueil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("DateDerniereModification")
                        .HasColumnType("datetime2");

                    b.Property<bool>("VisibleAuxInvites")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("MessageAccueil");
                });

            modelBuilder.Entity("Dataportal.Models.Metadonnee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Anonymiser")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoriserApi")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoriserLeTelechargement")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DernierMiseAJour")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("IdDonnees")
                        .HasColumnType("int");

                    b.Property<int?>("IdDonneesContexteEnvironnemental")
                        .HasColumnType("int");

                    b.Property<int?>("IdDonneesEventLogs")
                        .HasColumnType("int");

                    b.Property<int>("IdLicence")
                        .HasColumnType("int");

                    b.Property<int>("IdSite")
                        .HasColumnType("int");

                    b.Property<int?>("IdTypeEnergieRenouvelable")
                        .HasColumnType("int");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<int>("IdVisibilite")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NombreDeTelechargements")
                        .HasColumnType("int");

                    b.Property<int>("QualiteDesDonnees")
                        .HasColumnType("int");

                    b.Property<bool>("SeriesTemporelles")
                        .HasColumnType("bit");

                    b.Property<string>("TailleDesDonnees")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("TraitementEnCours")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdDonnees")
                        .IsUnique();

                    b.HasIndex("IdDonneesContexteEnvironnemental")
                        .IsUnique()
                        .HasFilter("[IdDonneesContexteEnvironnemental] IS NOT NULL");

                    b.HasIndex("IdDonneesEventLogs")
                        .IsUnique()
                        .HasFilter("[IdDonneesEventLogs] IS NOT NULL");

                    b.HasIndex("IdLicence");

                    b.HasIndex("IdSite");

                    b.HasIndex("IdTypeEnergieRenouvelable");

                    b.HasIndex("IdUtilisateur");

                    b.HasIndex("IdVisibilite");

                    b.ToTable("Metadonnee");
                });

            modelBuilder.Entity("Dataportal.Models.Metadonnee_Appareil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdAppareil")
                        .HasColumnType("int");

                    b.Property<string>("IdAppareilDansDonnees")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdMetadonnee")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAppareil");

                    b.HasIndex("IdMetadonnee");

                    b.ToTable("Metadonnee_Appareil");
                });

            modelBuilder.Entity("Dataportal.Models.NotebookApiAccessLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccessedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("BytesReturned")
                        .HasColumnType("bigint");

                    b.Property<int>("IdMetadonnee")
                        .HasColumnType("int");

                    b.Property<int?>("IdNotebookApiToken")
                        .HasColumnType("int");

                    b.Property<int?>("IdUtilisateur")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccessedAtUtc");

                    b.HasIndex("IdMetadonnee");

                    b.HasIndex("IdNotebookApiToken");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("NotebookApiAccessLogs");
                });

            modelBuilder.Entity("Dataportal.Models.NotebookApiToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("IdUtilisateur");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("NotebookApiTokens");
                });

            modelBuilder.Entity("Dataportal.Models.QualiteDonnees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("QualiteDonnees");
                });

            modelBuilder.Entity("Dataportal.Models.RateLimitEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("WindowEndUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("RateLimitEntries");
                });

            modelBuilder.Entity("Dataportal.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Dataportal.Models.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Emplacement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Site");
                });

            modelBuilder.Entity("Dataportal.Models.StatutDeLaDemande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("StatutDeLaDemande");
                });

            modelBuilder.Entity("Dataportal.Models.TypeEnergieRenouvelable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("TypeEnergieRenouvelable");
                });

            modelBuilder.Entity("Dataportal.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CompteActif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateApprobation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DernierLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionProfil")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FinLockout")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEntreprise")
                        .HasColumnType("int");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<string>("LienLinkedIn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("MfaCodeExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("MfaCodeHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("MfaEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbrEchecsAcces")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PasswordResetTokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdEntreprise");

                    b.HasIndex("IdRole");

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("Dataportal.Models.Visibilite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("Visibilite");
                });

            modelBuilder.Entity("Dataportal.Models.DemandeDeCompte", b =>
                {
                    b.HasOne("Dataportal.Models.Entreprise", "Entreprise")
                        .WithMany("DemandeDeComptes")
                        .HasForeignKey("IdEntreprise")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dataportal.Models.StatutDeLaDemande", "StatutDeLaDemande")
                        .WithMany("DemandeDeComptes")
                        .HasForeignKey("IdStatutDeLaDemande")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entreprise");

                    b.Navigation("StatutDeLaDemande");
                });

            modelBuilder.Entity("Dataportal.Models.DomaineEmail", b =>
                {
                    b.HasOne("Dataportal.Models.Entreprise", "Entreprise")
                        .WithMany("DomaineEmails")
                        .HasForeignKey("IdEntreprise")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("Dataportal.Models.Donnees", b =>
                {
                    b.HasOne("Dataportal.Models.QualiteDonnees", "QualiteDonnees")
                        .WithMany("Donnees")
                        .HasForeignKey("IdQualiteDonnees")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QualiteDonnees");
                });

            modelBuilder.Entity("Dataportal.Models.DonneesContexteEnvironnemental", b =>
                {
                    b.HasOne("Dataportal.Models.QualiteDonnees", "QualiteDonnees")
                        .WithMany("DonneesContexteEnvironnemental")
                        .HasForeignKey("IdQualiteDonnees")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QualiteDonnees");
                });

            modelBuilder.Entity("Dataportal.Models.DonneesEventLogs", b =>
                {
                    b.HasOne("Dataportal.Models.QualiteDonnees", "QualiteDonnees")
                        .WithMany("DonneesEventLogs")
                        .HasForeignKey("IdQualiteDonnees")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QualiteDonnees");
                });

            modelBuilder.Entity("Dataportal.Models.FichierStocke", b =>
                {
                    b.HasOne("Dataportal.Models.Licence", "Licence")
                        .WithMany()
                        .HasForeignKey("IdLicence")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dataportal.Models.TypeEnergieRenouvelable", "TypeEnergieRenouvelable")
                        .WithMany()
                        .HasForeignKey("IdTypeEnergieRenouvelable")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dataportal.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dataportal.Models.Visibilite", "Visibilite")
                        .WithMany()
                        .HasForeignKey("IdVisibilite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Licence");

                    b.Navigation("TypeEnergieRenouvelable");

                    b.Navigation("Utilisateur");

                    b.Navigation("Visibilite");
                });

            modelBuilder.Entity("Dataportal.Models.Metadonnee", b =>
                {
                    b.HasOne("Dataportal.Models.Donnees", "Donnees")
                        .WithOne("Metadonnee")
                        .HasForeignKey("Dataportal.Models.Metadonnee", "IdDonnees")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dataportal.Models.DonneesContexteEnvironnemental", "DonneesContexteEnvironnemental")
                        .WithOne("Metadonnee")
                        .HasForeignKey("Dataportal.Models.Metadonnee", "IdDonneesContexteEnvironnemental");

                    b.HasOne("Dataportal.Models.DonneesEventLogs", "DonneesEventLogs")
                        .WithOne("Metadonnee")
                        .HasForeignKey("Dataportal.Models.Metadonnee", "IdDonneesEventLogs");

                    b.HasOne("Dataportal.Models.Licence", "Licence")
                        .WithMany("Metadonnees")
                        .HasForeignKey("IdLicence")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dataportal.Models.Site", "Site")
                        .WithMany("Metadonnees")
                        .HasForeignKey("IdSite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dataportal.Models.TypeEnergieRenouvelable", "TypeEnergieRenouvelable")
                        .WithMany("Metadonnees")
                        .HasForeignKey("IdTypeEnergieRenouvelable")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dataportal.Models.Utilisateur", "Utilisateur")
                        .WithMany("Metadonnees")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dataportal.Models.Visibilite", "Visibilite")
                        .WithMany("Metadonnees")
                        .HasForeignKey("IdVisibilite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donnees");

                    b.Navigation("DonneesContexteEnvironnemental");

                    b.Navigation("DonneesEventLogs");

                    b.Navigation("Licence");

                    b.Navigation("Site");

                    b.Navigation("TypeEnergieRenouvelable");

                    b.Navigation("Utilisateur");

                    b.Navigation("Visibilite");
                });

            modelBuilder.Entity("Dataportal.Models.Metadonnee_Appareil", b =>
                {
                    b.HasOne("Dataportal.Models.Appareil", "Appareil")
                        .WithMany("Metadonnee_Appareils")
                        .HasForeignKey("IdAppareil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dataportal.Models.Metadonnee", "Metadonnee")
                        .WithMany("Metadonnee_Appareils")
                        .HasForeignKey("IdMetadonnee")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appareil");

                    b.Navigation("Metadonnee");
                });

            modelBuilder.Entity("Dataportal.Models.NotebookApiAccessLog", b =>
                {
                    b.HasOne("Dataportal.Models.Metadonnee", "Metadonnee")
                        .WithMany()
                        .HasForeignKey("IdMetadonnee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dataportal.Models.NotebookApiToken", "NotebookApiToken")
                        .WithMany()
                        .HasForeignKey("IdNotebookApiToken")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dataportal.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Metadonnee");

                    b.Navigation("NotebookApiToken");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Dataportal.Models.NotebookApiToken", b =>
                {
                    b.HasOne("Dataportal.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Dataportal.Models.Utilisateur", b =>
                {
                    b.HasOne("Dataportal.Models.Entreprise", "Entreprise")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("IdEntreprise")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dataportal.Models.Role", "Role")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entreprise");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Dataportal.Models.Appareil", b =>
                {
                    b.Navigation("Metadonnee_Appareils");
                });

            modelBuilder.Entity("Dataportal.Models.Donnees", b =>
                {
                    b.Navigation("Metadonnee")
                        .IsRequired();
                });

            modelBuilder.Entity("Dataportal.Models.DonneesContexteEnvironnemental", b =>
                {
                    b.Navigation("Metadonnee")
                        .IsRequired();
                });

            modelBuilder.Entity("Dataportal.Models.DonneesEventLogs", b =>
                {
                    b.Navigation("Metadonnee")
                        .IsRequired();
                });

            modelBuilder.Entity("Dataportal.Models.Entreprise", b =>
                {
                    b.Navigation("DemandeDeComptes");

                    b.Navigation("DomaineEmails");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("Dataportal.Models.Licence", b =>
                {
                    b.Navigation("Metadonnees");
                });

            modelBuilder.Entity("Dataportal.Models.Metadonnee", b =>
                {
                    b.Navigation("Metadonnee_Appareils");
                });

            modelBuilder.Entity("Dataportal.Models.QualiteDonnees", b =>
                {
                    b.Navigation("Donnees");

                    b.Navigation("DonneesContexteEnvironnemental");

                    b.Navigation("DonneesEventLogs");
                });

            modelBuilder.Entity("Dataportal.Models.Role", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("Dataportal.Models.Site", b =>
                {
                    b.Navigation("Metadonnees");
                });

            modelBuilder.Entity("Dataportal.Models.StatutDeLaDemande", b =>
                {
                    b.Navigation("DemandeDeComptes");
                });

            modelBuilder.Entity("Dataportal.Models.TypeEnergieRenouvelable", b =>
                {
                    b.Navigation("Metadonnees");
                });

            modelBuilder.Entity("Dataportal.Models.Utilisateur", b =>
                {
                    b.Navigation("Metadonnees");
                });

            modelBuilder.Entity("Dataportal.Models.Visibilite", b =>
                {
                    b.Navigation("Metadonnees");
                });
#pragma warning restore 612, 618
        }
    }
}
